spring:
  application:
    name: quartz_learn
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/quartz_learn?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  quartz:
    jdbc:
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.isClustered: true
